import importlib.util
import pathlib
import tempfile
import unittest


MODULE_PATH = (
    pathlib.Path(__file__).parents[1] / "klipper" / "nozzle_guard.py"
)
SPEC = importlib.util.spec_from_file_location("nozzle_guard", MODULE_PATH)
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)
NozzleMetadataParser = MODULE.NozzleMetadataParser
NozzleGuardModel = MODULE.NozzleGuardModel
NozzleGuard = MODULE.NozzleGuard


class NozzleMetadataParserTest(unittest.TestCase):
    def test_reads_orca_style_configuration_comment(self):
        values, source = NozzleMetadataParser.parse(
            "; generated by OrcaSlicer\n"
            "; nozzle_diameter = 0.8\n"
        )
        self.assertEqual(values, [0.8])
        self.assertIn("nozzle_diameter", source)

    def test_reads_multiple_extruders(self):
        values, _ = NozzleMetadataParser.parse(
            "; nozzle diameter = 0.4, 0.6\n"
        )
        self.assertEqual(values, [0.4, 0.6])

    def test_ignores_template_variables(self):
        values, _ = NozzleMetadataParser.parse(
            "; nozzle_diameter = [nozzle_diameter]\n"
        )
        self.assertEqual(values, [])


class NozzleGuardModelTest(unittest.TestCase):
    def test_match_allows_start(self):
        model = NozzleGuardModel(0.4)
        model.inspect("part.gcode", "; nozzle_diameter = 0.4\n")
        self.assertEqual(model.state, "match")
        self.assertFalse(model.blocks_start())

    def test_confirmed_mismatch_blocks_by_default(self):
        model = NozzleGuardModel(0.4)
        model.inspect("part.gcode", "; nozzle_diameter = 0.8\n")
        self.assertEqual(model.state, "mismatch")
        self.assertTrue(model.blocks_start())

    def test_unknown_metadata_warns_but_allows(self):
        model = NozzleGuardModel(0.4)
        model.inspect("part.gcode", "; generated without config dump\n")
        self.assertEqual(model.state, "unknown")
        self.assertFalse(model.blocks_start())

    def test_override_is_scoped_to_selected_file(self):
        model = NozzleGuardModel(0.4)
        model.inspect("wrong.gcode", "; nozzle_diameter = 0.8\n")
        self.assertTrue(model.override_once())
        self.assertEqual(model.state, "overridden")
        self.assertFalse(model.blocks_start())
        model.inspect("another.gcode", "; nozzle_diameter = 0.8\n")
        self.assertEqual(model.state, "mismatch")
        self.assertTrue(model.blocks_start())

    def test_warn_mode_never_blocks(self):
        model = NozzleGuardModel(0.4, mode="warn")
        model.inspect("wrong.gcode", "; nozzle_diameter = 0.8\n")
        self.assertEqual(model.state, "mismatch")
        self.assertFalse(model.blocks_start())

    def test_installed_registry_tool_becomes_active_reference(self):
        model = NozzleGuardModel(0.4)
        model.inspect("part.gcode", "; nozzle_diameter = 0.8\n")
        self.assertTrue(model.blocks_start())
        model.set_installed_tool(0.8, "hardened-08", "Hardened 0.8")
        status = model.get_status()
        self.assertEqual(status["state"], "match")
        self.assertEqual(status["comparison_source"], "registry")
        self.assertEqual(status["klipper_nozzle"], 0.4)
        self.assertEqual(status["configured_nozzle"], 0.8)
        self.assertFalse(model.blocks_start())

    def test_clearing_registry_tool_restores_klipper_reference(self):
        model = NozzleGuardModel(0.4)
        model.inspect("part.gcode", "; nozzle_diameter = 0.8\n")
        model.set_installed_tool(0.8, "hardened-08")
        self.assertEqual(model.state, "match")
        model.clear_installed_tool()
        self.assertEqual(model.state, "mismatch")
        self.assertEqual(model.get_status()["comparison_source"], "klipper")

    def test_rejects_invalid_registry_profile(self):
        model = NozzleGuardModel(0.4)
        with self.assertRaises(ValueError):
            model.set_installed_tool(0.8, "bad profile id")




class NozzleGuardToolChangeSafetyTest(unittest.TestCase):
    class Gcmd:
        @staticmethod
        def error(message):
            return RuntimeError(message)

    def test_tool_reference_change_is_blocked_while_printing_or_paused(self):
        for state in ("printing", "paused"):
            guard = NozzleGuard.__new__(NozzleGuard)
            guard.reactor = type("Reactor", (), {"monotonic": lambda self: 12.0})()
            guard.print_stats = type("PrintStats", (), {
                "get_status": lambda self, eventtime, current=state: {"state": current}
            })()
            with self.assertRaisesRegex(RuntimeError, "cannot change"):
                guard._assert_tool_change_idle(self.Gcmd())

    def test_tool_reference_change_fails_closed_without_print_state(self):
        guard = NozzleGuard.__new__(NozzleGuard)
        guard.print_stats = None
        with self.assertRaisesRegex(RuntimeError, "cannot verify"):
            guard._assert_tool_change_idle(self.Gcmd())


class NozzleGuardFileReadTest(unittest.TestCase):
    def test_scans_tail_without_loading_whole_gcode(self):
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "large.gcode"
            path.write_bytes(
                b"G1 X0\n" + b"G1 X1\n" * 2000
                + b"; nozzle_diameter = 0.8\n"
            )
            guard = NozzleGuard.__new__(NozzleGuard)
            guard.scan_bytes = 128
            text = guard._read_metadata_text(str(path))
            values, _ = NozzleMetadataParser.parse(text)
            self.assertEqual(values, [0.8])
            self.assertLess(len(text), 300)


if __name__ == "__main__":
    unittest.main()
